### PR TITLE
[`Docs`] Update bnb installation guidelines for users that want to install bnb from source

### PR DESCRIPTION
**Pull request by younesbelkada**
Hi! 

Thanks for this great work!
I noticed that in the readme you mention to use `make` commands to install bnb from source. Note the Makefile has been removed in favor of CMake and the Makefile cannot be found here: https://github.com/AnswerDotAI/bitsandbytes 
As the commits to add FSDP support has been upstreamed into bnb main, I propose to reflect the readme to the official installation guidelines that properly guides users on how to install bnb from source

cc @jph00

### CODE REVIEW

**Comment by warner-benjamin** [comment]
@younesbelkada I updated the ReadMe in 6b7cdb5, which includes updated bitsandbytes installation instructions. Once bitsandbytes 0.43 is released we'll remove the custom installation instructions and only have the pip install.

**Comment by younesbelkada** [comment]
Thanks @warner-benjamin the release should be live in the next couple of minutes 

cc @Titus-Von-Koeller

**Comment by younesbelkada** [comment]
@warner-benjamin bnb 0.43.0 is now live: https://pypi.org/project/bitsandbytes/

**Comment by warner-benjamin** [comment]
Resolved with 47c1722

**Pull request closed without merging**
